### ISSUE TITLE
Footer Menu

### ISSUE THREAD

**Issue by pmadiset** [pmadiset/DealerApp#8] opened 2017-07-30 11:29 UTC
- [x] 1. Change the title "Sim Change" to "SIM Change"
- [x] 2. Animation --> When the footer is slide to left, then (While the tap is on) the same menu slides from right to left and then that disappears and the actual menu appears.

**Comment by mobiloitte-quality** [comment] 2017-07-31 14:46
**Mobiloitte comment:** Done

**Comment by pmadiset** [comment] 2017-08-01 04:58
Animation is still not correct.

**Comment by pmadiset** [comment] 2017-08-01 11:56
Please check the screenshot below. When I am scrolling the footer (Dash Baord, SIM change, and Requests) towards left, the same thing (Dash Baord, SIM change, and Requests) comes from right instead of next one (Reports, Contact Us, Help)

![image](https://user-images.githubusercontent.com/30493900/28824131-c018f8ca-76d1-11e7-8945-d34d8240397d.png)

**Comment by mobiloitte-quality** [comment] 2017-08-01 12:34
**Mobiloitte Comment:** This will be done during functional milestone
release.

**Comment by mjov** [comment] 2017-08-21 08:01
@pmadiset 
i believe this issue is resolved, if you are ok, let's close this ticket

**Comment by pmadiset** [comment] 2017-08-21 08:49
This is not yet done.

**Comment by mjov** [comment] 2017-08-21 09:33
you are right Praveen, on the slow swipe from right-to-left, we can clearly see that scroll starts with Dashboard icon, instead, reports @mobiloitte-quality (FYI/A)

**Comment by mjov** [comment] 2017-08-23 14:04
the issue is still present, please check the video link below:
https://www.dropbox.com/s/qpzxkln5v1qmt18/Video%20Aug%2023%2C%2017%2009%2048.mov?dl=0

**Comment by mobiloitte-quality** [comment] 2017-08-23 14:17
Hi @mjov / @pmadiset  ,

We have done on the point footer menu animation and making company fields optional.. Shall I provide new apk? And you begin testing on that?

As mentioned, please find below the link:

Please look into the build below, we have done with the requirement shared by you. 
ftp link:  http://ec2-52-1-133-240.compute-1.amazonaws.com/FTP-LOCATION/RennaDealer1.8.apk

**Comment by mjov** [comment] 2017-08-23 15:00
Hi,

Do You have new build with resolved footer animation and non-mandatory
fields under Company section ?

You can rebuild same Ver1.8 so we provide you the comments on that build by
tomorrow

Regards
Milan

**Closed** 2017-08-28 12:44 UTC
